--- 
kind: pipeline
name: dvstLab
steps: 
  - name: compile-beta-lite
    image: "rzlamrr/dvstlab:lite"
    commands: 
      - "apt update -qq -y && DEBIAN_FRONTEND=noninteractive apt install -qq -y openjdk-8-jdk"
      - "git clone https://github.com/dvstLab/ginkgo-kernel -b temp silont"
      - "rm -rf .git"
      - "cd silont"
      - "wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/compile.sh"
      - "chmod +x compile.sh"
      - "bash compile.sh -gcc eva -d vendor/ginkgo-perf_defconfig -cn Beta"
      - "cd .. && rm -rf *"
    environment: 
      CHATID: -1001203110683
      TOKED: 
        from_secret: TOKED
